apiVersion: v1
entries:
  kminion:
  - apiVersion: v2
    appVersion: v2.0.0
    created: "2021-02-21T23:01:39.732095727Z"
    description: A Helm chart to deploy KMinion - a Prometheus Exporter for Apache Kafka
    digest: f65dee98ea05ade826f68895e7bcebd8ebe44c37f9c3f628a3ed011855f03e91
    name: kminion
    type: application
    urls:
    - kminion-0.2.1.tgz
    version: 0.2.1
  - apiVersion: v2
    appVersion: v2.0.0
    created: "2021-02-21T23:01:39.730564224Z"
    description: A Helm chart to deploy KMinion - a Prometheus Exporter for Apache Kafka
    digest: 025661ee7cc574ad8dde7a68093a3b614fc92e26dd5dd398fc89d0b5308010e1
    name: kminion
    type: application
    urls:
    - kminion-0.2.0.tgz
    version: 0.2.0
  - apiVersion: v2
    appVersion: v2.0.0
    created: "2021-02-21T23:01:39.729642523Z"
    description: A Helm chart to deploy KMinion - a Prometheus Exporter for Apache Kafka
    digest: e277e976d864b4bd2e505038dd865a9300486ae8c4323d3f0be40b84df75732b
    name: kminion
    type: application
    urls:
    - kminion-0.1.3.tgz
    version: 0.1.3
  - apiVersion: v2
    appVersion: v2.0.0
    created: "2021-02-21T23:01:39.72250311Z"
    description: A Helm chart to deploy KMinion - a Prometheus Exporter for Apache Kafka
    digest: 562937d3613624c55984e51adbc6765e7898d1cf8cc2d7d241b6d671bbc12303
    name: kminion
    type: application
    urls:
    - kminion-0.1.2.tgz
    version: 0.1.2
  - apiVersion: v2
    appVersion: v2.0.0
    created: "2021-02-21T23:01:39.721871909Z"
    description: A Helm chart to deploy KMinion - a Prometheus Exporter for Apache Kafka
    digest: 25e83d7c7cc92a63268d76b13ecc13077758b48be093490f281498a4f55ad3ca
    name: kminion
    type: application
    urls:
    - kminion-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v2
    appVersion: v2.0.0
    created: "2021-02-21T23:01:39.721228507Z"
    description: A Helm chart to deploy KMinion - a Prometheus Exporter for Apache Kafka
    digest: 7c10e9d9957e9752bc6f4b4a1fffb742d88cd57be06bf4f26ff7b5031645ccbd
    name: kminion
    type: application
    urls:
    - kminion-0.1.0.tgz
    version: 0.1.0
generated: "2021-02-21T23:01:39.720359406Z"
