apiVersion: v1
kind: ConfigMap
metadata:
  name: {{include "kminion.fullname" .}}
  labels:
    {{- include "kminion.labels" . | nindent 4}}
data:
  config.yaml: |
    {{- toYaml .Values.kminion.config | nindent 4}}