name: Package helm chart on push

on:
  push:
    branches:
      - master
    paths:
      - 'charts/**'
      - '!charts/**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Helm Package
        run: |
          helm package ./charts/kminion -d ./charts/archives
      - name: Helm Index
        run: |
          helm repo index ./charts/archives --merge .charts/archives/index.yaml
      - name: Commit and push
        run: |
          git config user.name "GitHub Action ($GITHUB_ACTOR)"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add --all
          git commit -m  '[Auto Commit] Package helm chart'
          git push